name: Check Release and Do Something

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "릴리스 이름을 입력하세요 (예: Release v1.2.3)"
        required: true

jobs:
  check-release-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check if release with given name exists
        id: check_release
        uses: actions/github-script@v6
        with:
          script: |
            const releaseName = "${{ github.event.inputs.release_name }}"
            const releases = await github.paginate(
              github.rest.repos.listReleases,
              {
                owner: context.repo.owner,
                repo: context.repo.repo
              }
            )
            const found = releases.find(r => r.name === releaseName)
            if (found) {
              core.info(`✅ Release "${releaseName}" found (tag: ${found.tag_name})`)
              core.setOutput("exists", "true")
              core.setOutput("tag", found.tag_name)
            } else {
              core.setFailed(`❌ Release "${releaseName}" not found.`)
            }

      - name: Run script only if release exists
        if: steps.check_release.outputs.exists == 'true'
        run: |
          echo "Running deployment for release..."
          echo "Release tag: ${{ steps.check_release.outputs.tag }}"
          # 예: curl로 배포 API 호출, 바이너리 다운로드, 서버 전개 등